name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there! Thanks for taking the time to contribute to Dragnipur. Post any questions you have here and feel free to check the issues page for starter issues.'
        pr-message: 'You''ve done it! You just created your first Pull Request on this repo. Congratulations 🎉!' 
